FROM node:22.23.2-alpine AS dependencies

WORKDIR /app
RUN corepack enable && corepack prepare pnpm@11.25.0 --activate
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./
RUN pnpm install --frozen-lockfile

FROM dependencies AS build
WORKDIR /app
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
ARG BUILD_DATABASE_URL
ARG BUILD_BETTER_AUTH_SECRET
ARG BUILD_BETTER_AUTH_URL
ARG BUILD_BETTER_AUTH_TRUSTED_ORIGINS
ARG BUILD_BETTER_AUTH_TRUSTED_PROXIES
ARG BUILD_EMAIL_VERIFICATION_ENABLED
ARG BUILD_GENERATION_RATE_LIMIT_WINDOW_SECONDS
ARG BUILD_GENERATION_RATE_LIMIT_MAX_REQUESTS
RUN \
  DATABASE_URL="$BUILD_DATABASE_URL" \
  BETTER_AUTH_SECRET="$BUILD_BETTER_AUTH_SECRET" \
  BETTER_AUTH_URL="$BUILD_BETTER_AUTH_URL" \
  BETTER_AUTH_TRUSTED_ORIGINS="$BUILD_BETTER_AUTH_TRUSTED_ORIGINS" \
  BETTER_AUTH_TRUSTED_PROXIES="$BUILD_BETTER_AUTH_TRUSTED_PROXIES" \
  EMAIL_VERIFICATION_ENABLED="$BUILD_EMAIL_VERIFICATION_ENABLED" \
  GENERATION_RATE_LIMIT_WINDOW_SECONDS="$BUILD_GENERATION_RATE_LIMIT_WINDOW_SECONDS" \
  GENERATION_RATE_LIMIT_MAX_REQUESTS="$BUILD_GENERATION_RATE_LIMIT_MAX_REQUESTS" \
  pnpm build

FROM node:22.23.2-alpine AS runtime

WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
RUN corepack enable && corepack prepare pnpm@11.25.0 --activate
COPY --from=build /app ./

EXPOSE 3000
CMD ["pnpm", "start"]
